### ISSUE TITLE
Where to donate!?

### ISSUE THREAD

**Issue by 6-AND-9** [elias-sundqvist/obsidian-annotator#12]
Hi again,

I searched your website but couldn't find where one can donate to the plugin. Is this possible? Do you accept donations?

Regards,
6-9

**Comment by elias-sundqvist** [comment]
Thanks for showing interest in donating 😄 
I'm just doing this because I like it, so I didn't expect anyone to give me money for it. But it certainly wouldn't hurt. 

I've now added donation links to the README of the repo. 
(Might take a day or so before the GitHub Sponsors link starts working though. )
