### ISSUE TITLE
Not able to open PDF from cloud

### ISSUE THREAD

**Issue by username-8** [elias-sundqvist/obsidian-annotator#134]
we've discussed this [here](https://discord.com/channels/686053708261228577/707816848615407697/943452548864561212), [here](https://discord.com/channels/686053708261228577/707816848615407697/943457169272107008)  & [here](https://discord.com/channels/686053708261228577/707816848615407697/943458124579373077)

I've tried to annotate files from adobe document cloud using the share link function in adobe 
![image](https://user-images.githubusercontent.com/80767842/154260365-5eaa1e31-c05a-44fa-a2ac-003c8c413442.png)

but it's not opening and shows this error
![image](https://user-images.githubusercontent.com/80767842/154260494-1842c091-95a2-4a38-ab6e-59b812e7deec.png)

----
and if possible find a way to update the annotation in original/source file

**Comment by elias-sundqvist** [comment]
I checked the URL in your example on discord now. The reason that it doesn't work is that you need a direct URL to a pdf. The URL that you used points to a website where you review pdfs. I'm not sure whether adobe has the ability to share direct links to pdfs.

In your case, since Adobe Document Cloud has it's own annotation features, you might as well use them. You can do it using an iframe like this.

```md
<iframe src="https://acrobat.adobe.com/link/review?uri=urn%3Aaaid%3Ascds%3AUS%3A78d90085-4368-403b-a17b-a206d5b33829" width=100% height=1000px/>
```

**Comment by username-8** [comment]
Ooo... so that's why... thanx for the swift response 
& nice idea on the iframe 
Imma try that soon as I wake up
Have a good day/night

Thanx👋

**Comment by andrewcrook** [comment]
I recently found that direct file loading through HTTP and HTTPS is broken the issue #151
