### ISSUE TITLE
How do you update hypothesis?

### ISSUE THREAD

**Issue by aladmit** [elias-sundqvist/obsidian-annotator#138]
I was trying to debug DOMException error occurs each time plugin opens an epub/pdf document. I've found that plugin has this issue since [15 Jan](https://github.com/elias-sundqvist/obsidian-annotator/commit/2b18da63dceaef95e959d44b1e05f74979d8b021). Specifically it happened after changes in `resources/cdn.hypothes.is/hypothesis/1.960.0/build/scripts/annotator.bundle.js` file.

So, wondered if I can fix this error just by updating the bundle, but didn't find anything on how to do that :(

> DOMException: Failed to execute 'postMessage' on 'Window': Port at index 0 is already neutered.

**Comment by elias-sundqvist** [comment]
Regarding the particular issue that you're trying to fix. I think it will probably be easier if I fix it. The issue likely lies in my [react-offline-iframe](https://github.com/elias-sundqvist/react-offline-iframe) package. I need to check whether communication ports have been closed before forwarding any postMessage events. 

I can still describe how to update hypothesis, since you might want to do that for other reasons at some point. 🙂

The process of updating hypothesis is a bit tedious and manual, but these are the basic steps: 

1. Get the [Save All Resources](https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb) extension: 
2. Visit https://via.hypothes.is/https://arxiv.org/pdf/1702.08734.pdf
3. Use the save all resources plugin to download the website. 
4. Open the zip file and drag the folders "cdn.hypothes.is", "hypothes.is", and "via.hypothes.is" into the resources folder. 
5. For any affected files, make  the changes listed in `Modified Resources.md`
6. You may also have to search for instances of the old hypothesis version number in the code and replace them with the new version number.

**Comment by aladmit** [comment]
I've tried to update and... That's a hell of task 😭

I downloaded https://via.hypothes.is/https://arxiv.org/pdf/1702.08734.pdf and https://cdn.hypothes.is/demos/epub/epub.js/index.html (because it contains demo/epub), extracted them to `resources/`.

Unfortunately, it's really not trivial to add changes from `Modified Resources.md` :(
Sometimes it's hard to understand what changes should be made(even in cases where I was author of a change), sometimes it's impossible to make a change, because original file change too much and there is no code code like in `Modified Resources.md`.

I don't see any DOMException right now, but maybe that's because I failed to make all modifications. PDF reader completely ruined with `Error: The `container` must be absolutely positioned.` error.

I'll try again tomorrow, but we definitely need to find another way to update all this. Current way is too hard))

**Comment by elias-sundqvist** [comment]
> That's a hell of task 😭 [...] we definitely need to find another way to update all this. Current way is too hard))

Agreed. In the future I think we should have a fork of https://github.com/hypothesis/client as a submodule for this project, and a script to build the latest version automatically. 
This would also mean that we can have a branch with our custom changes, and just do a merge whenever a new version of hypothesis comes out. So we won't need the `Modified Eesources.md` file then.

**Comment by aladmit** [comment]
Are you sure we need our own fork? I don't understand how the plugin works with hypothesis lib yet, but maybe there is chance to use it just as a library with params or a wapper around?

**Comment by HardwayLinka** [comment]
Is this problem solved? The same problem occurs when I click the link with the left mouse button and the console shows: 
![image](https://user-images.githubusercontent.com/45873697/167879998-aa958e91-2466-4286-a54a-f3054f9c767b.png)
and the pdf is not positioned to the corresponding highlight

**Comment by aladmit** [comment]
Yes, fix of the issue already in master, but it's not released yet

**Comment by elias-sundqvist** [comment]
Sorry for not being very quick with new releases. I'm busy working on my masters thesis at the moment, and I know from experience that I will get flooded with issues whenever I make a new release (somehow I always manage to introduce a new bug or two :/), and I won't have the time to deal with them.

@aladmit If you want to release things more quickly, I would be fine with giving you partial ownership of the repo. Would you be interested in that?

**Comment by HardwayLinka** [comment]
@aladmit when will it be released, i can't wait /(ㄒoㄒ)/~~

**Comment by aladmit** [comment]
@elias-sundqvist I'm in ❤️ And I would like to have write permissions to hypothesis fork to keep it up to date.

**Comment by elias-sundqvist** [comment]
Great! I've sent you invites to the repositories now.

**Comment by aladmit** [comment]
Good news: I updated hypothesis and released 0.2.2 version 

Bad news: I messed up tags and versions somehow, so we have 0.2.2 version with 0.2.3 git tag 😆😭
