### ISSUE TITLE
Query: Version conflict

### ISSUE THREAD

**Issue by spiritualgeek** [elias-sundqvist/obsidian-annotator#148]
It seems as if you've released v0.2.0 but on obsidian it shows v0.1.9?

**Comment by aladmit** [comment]
That's because 0.2.0 released as beta version. Yes, there is a few cool new features, but they a little buggy at the moment. If you okay with that, you can install 0.2.0 through https://github.com/TfTHacker/obsidian42-brat plugin.

How to do that:
1. Install BRAT plugin
2. Uninstall obsidian-annotator
3. Add obsidian-annotator through BRAT plugin

<img width="897" alt="Screenshot 2022-02-27 at 21 50 11" src="https://user-images.githubusercontent.com/4015182/155895603-13ad2a9f-3b4b-4572-8f8a-60ffd5c9e6d9.png">

4. Enable obsidian-annotator in Community Plugins -> Installed plugins

**Comment by spiritualgeek** [comment]
Thanks - I should have read on. Silly me.

Have high hopes for this plugin and will start actively using it soon :)
