### ISSUE TITLE
Epub annotations dissapear after page turn

### ISSUE THREAD

**Issue by xBlady** [elias-sundqvist/obsidian-annotator#153]
I see that Epub annotations dissapear after page turn. Example in a video - https://youtu.be/t9DG01PaG4k?t=379

I've checked epub 2 and epub 3 file formats.

**Comment by ryanwwest** [comment]
I've noted similar disappearing behavior on Windows on version 0.2.1. In fact, I often can't get them to load at all if I enter annotation mode without using the 'show annotation' link for an annotation in markdown mode. And even if I do that and it takes me to the right page, annotations still sometimes  don't show up. Things usually work fine on my macos laptop with the vault (+plugin configs) synced.

**Comment by ryanwwest** [comment]
I take it back - the EPUB annotations intermittently disappear on MacOS, Windows, and Android.

**Comment by aladmit** [comment]
I see this bug pretty regularly too 😢 Part of the problem is how hypothesis annotations integrates with epub reader. I also noticed that you can see only annotations for chapter you see at the moment. For example, you highlighted first chapter and see annotations in the sidebar, but they disappear as soon as you open second chapter.

It really annoys me too, so I'm going to try to fix that as soon we will finish [this PR](https://github.com/elias-sundqvist/obsidian-annotator/pull/141)

**Comment by aladmit** [comment]
Looks like the latest release fixed the issue 👍🏻

**Comment by MiracleXYZ** [comment]
> you can see only annotations for chapter you see at the moment

This is happening now again. Sometimes it's not even the current chapter but the current section...
