### ISSUE TITLE
Clicking on link to jump to annotation causes PDF to scroll up and down repeatedly

### ISSUE THREAD

**Issue by cyrulnik** [elias-sundqvist/obsidian-annotator#21]
Thanks for this amazing plugin. 

I am seeing behavior that seems like a bug -- when I click on a link to an annotation to Obsidian, it opens the PDF, scrolls to the point of the annotation, then immediately scrolls put to the top, then back down to the annotation -- and it does this in a loop for two or three cycles.

**Comment by GitMurf** [comment]
Yes I am seeing this too. Sometimes it keeps scrolling up and down several times and then eventually just lands on the very top of the pdf.

@elias-sundqvist are you aware of this / know what we are talking about? Or would you like us to provide a screen recording of it?

**Comment by elias-sundqvist** [comment]
Yeah, I'm aware of the issue. It's mostly an hypothes.is issue (If you click an annotation card it sometimes brings you to the top of the page instead of going to the annotation). But it looks extra janky with my implementation because I essentially click the card multiple times until the scrolling stops. I'll try to find a better approach.

**Comment by elias-sundqvist** [comment]
Yeah, I haven't gotten around to fixing this yet. Maybe in the next release.

**Comment by elias-sundqvist** [comment]
This should now be fixed (for pdfs) in the new release.
