### ISSUE TITLE
annotator catches every keyboard input, even when not active

### ISSUE THREAD

**Issue by bitSheriff** [elias-sundqvist/obsidian-annotator#215]
if you have annotator in a second pane opened, and you navigate with the arrow-keys, the annotator catches these inputs and moves to the next page, even if the pane is not selected

Annotator-Version: 0.2.6
Obsidian-Version: 0.15.9

**Comment by bitSheriff** [comment]
[Screencast from 20.08.2022 20:00:06.webm](https://user-images.githubusercontent.com/44727821/185760362-f8a909f0-6053-4dab-ac51-43c307541d62.webm)

**Comment by qiaogaojian** [comment]
same issue
Annotator-Version: 0.2.2
Obsidian-Version: 0.14.15

**Comment by bitSheriff** [comment]
Probably the problem is in the file `defineEpubAnnotation.tsc`
![grafik](https://user-images.githubusercontent.com/44727821/198847441-65e7108e-310f-4a7b-9a56-5facc0edb818.png)

A good solution would be to check the context, if the annotator pane is currently focused. 
Sadly, I don't have any experience in TypeScript. Another solution would be to have another (boolean) settings which turns off the page turning by the arrow keys.

@elias-sundqvist any idea if this bug will get fixed soon?

**Comment by aladmit** [comment]
This code in `defineEpubAnnotation` executes only when epub reader open, but the but persists in all other annotation modes too(web, YouTube, pdf). That's why I think that's an [issue with iframe](https://github.com/elias-sundqvist/obsidian-annotator/issues/161#issuecomment-1126774893).

> any idea if this bug will get fixed soon?

I'll not to be able to develop the plugin for a few more months. So, maybe it will be fixed somewhere in January, I don't know, it's hard to say right know.

P.S. I'm closing this issue because it's a dup of #161

**Comment by bitSheriff** [comment]
Thanks for the clarification :)
